platform :tvos, '12.0'

target 'DolphiniOS' do
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    #pod 'UICollectionViewLeftAlignedLayout'
end

target 'DolphiniOS-TV' do
    pod 'Firebase'
    #pod 'UICollectionViewLeftAlignedLayout'
end
